"""foff

Revision ID: 4661c7ae0d7a
Revises: 070c137cf035
Create Date: 2024-01-24 23:57:59.790669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4661c7ae0d7a'
down_revision: Union[str, None] = '070c137cf035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('date_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_price_id'), 'sub_price', ['id'], unique=False)
    op.add_column('catalog_img', sa.Column('business_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'catalog_img', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('sub_history', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('sub_history', sa.Column('date_created', sa.Date(), server_default=sa.text('now()'), nullable=False))
    op.add_column('subscriptions', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('subscriptions', sa.Column('date_created', sa.Date(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'date_created')
    op.drop_column('subscriptions', 'price')
    op.drop_column('sub_history', 'date_created')
    op.drop_column('sub_history', 'price')
    op.drop_constraint(None, 'catalog_img', type_='foreignkey')
    op.drop_column('catalog_img', 'business_id')
    op.drop_index(op.f('ix_sub_price_id'), table_name='sub_price')
    op.drop_table('sub_price')
    # ### end Alembic commands ###
