"""location

Revision ID: b6af9b4e8d38
Revises: 8cb74c37985f
Create Date: 2024-01-05 10:51:39.014749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6af9b4e8d38'
down_revision: Union[str, None] = '8cb74c37985f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('location', sa.String(), nullable=True))
    op.alter_column('business', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('business', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_favorite_id'), 'favorite', ['id'], unique=False)
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.alter_column('users', 'phone_verified',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_verified',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_favorite_id'), table_name='favorite')
    op.alter_column('business', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('business', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('business', 'location')
    # ### end Alembic commands ###
